# Generated by Django 5.0 on 2024-06-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Donor'), (3, 'Buyer')], default=1),
        ),
    ]
